### ISSUE TITLE
100 is a possible target

### ISSUE THREAD

**Issue by Nixill** [elocemearg/numsolver#2]
Regarding desktop.html: As shown on the 29 Nov 2023 episode of Countdown, it's still possible for CECIL to pick 100 as a target, and thus I believe it should be listed in the Map.

**Comment by elocemearg** [comment]
Thanks - this is already fixed in commit 9004f84b two days ago.

**Comment by Nixill** [comment]
🤦‍♀️ I can't believe I've done that. Apologies.
